services:
  chirpd:
    build: .
    container_name: chirpd
    volumes:
      - ./data:/etc/rspamd/dkim:ro
      - ./users:/etc/dovecot/users:ro
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - MAIL_HOST=${MAIL_HOST}
    ports:
      - "127.0.0.1:25:25" # Bind to localhost:25
    restart: unless-stopped
    networks:
      - chirpd_net

networks:
  chirpd_net:
    driver: bridge
