#!/bin/bash
DATA_DIR=./data

if [ ! -d "$DATA_DIR" ]; then
    mkdir "$DATA_DIR"
fi

# Load DOMAIN and MAIL_HOST from .env file
source ./.env

# Generate DKIM keys
rspamadm dkim_keygen -s mail -b 2048 -d "$DOMAIN" -k "$DATA_DIR/$DOMAIN.mail.key" > "$DATA_DIR/$DOMAIN.mail.txt"

# Create DNS TXT record file
DNS_RECORD=$(cat "$DATA_DIR/$DOMAIN.mail.txt" | grep -v DKIM | tr -d '\n' | sed 's/^[^"]*"//' | sed 's/"$//')
echo "mail._domainkey.$DOMAIN IN TXT \"v=DKIM1; k=rsa; $DNS_RECORD\"" > "$DATA_DIR/dkim_dns_record.txt"

echo "DKIM keys generated and configuration files created in $DATA_DIR"
